### ISSUE TITLE
Error while buidling on windows 7 with Qt 5.8 and MSVC2015_64bit

### ISSUE THREAD

**Issue by schalll** [jbagg/QtZeroConf#10]
I would really like to build zeroconf into one of my project, but building on windows I am getting an error on line 136 from the generated moc_qzeroconf.cpp in function

```
const QMetaObject QZeroConf::staticMetaObject = {
    { &QObject::staticMetaObject, qt_meta_stringdata_QZeroConf.data,
      qt_meta_data_QZeroConf,  qt_static_metacall, Q_NULLPTR, Q_NULLPTR}
};
```
saying C2491: 'QZeroConf::staticMetaObject': definition of dllimport static data member not allowed.

**Comment by jbagg** [comment]
Hello.  Is this happening with the most recent code with Q_DECL_EXPORT added?  (9 days ago).  I've tested with win7 msvc 2015 and Qt5.8.  Today I hope to test the same on win 10.

**Comment by 0x000000FF** [comment]
hi~I got the same error,Windows 10 with MSVC2015_64bit,Qt 5.7.0.
And yes, with Q_DECL_EXPORT added.I rescind this change and it worked.
Thanks!

**Comment by jbagg** [comment]
I found the problem and pushed a fix.  You will also need to add
DEFINES= QZEROCONF_STATIC
to your project's .pro file.  Please provide feedback (so we can close)

**Comment by jbagg** [comment]
I tested building QtZeroConf into projects both ways, as a DLL and statically / directly included in the projects build.
