### ISSUE TITLE
the host is empty

### ISSUE THREAD

**Issue by 0x000000FF** [jbagg/QtZeroConf#11]
I test the browser,I found that the host string is empty(""),but my service truly published with the host string,I can get it by my python code.I need this string ,is there a way to solve this?Thanks!

**Comment by 0x000000FF** [comment]
in file bonjour.cpp,line 194,after 
`if (hAddress.protocol() == QAbstractSocket::IPv6Protocol)
				ref->newService->ipv6 = hAddress;
			else
				ref->newService->ip = hAddress;`
I insert this line
`ref->newService->host = hostName;`

and it shows hostname.
thanks

**Comment by jbagg** [comment]
Yes, it looks like hostname was missing ios/macos/windows.  Do you want to make a pull request for me?

**Comment by jbagg** [comment]
...the Q_UNUSED(hostName); line 180 should be removed as well.

**Comment by jbagg** [comment]
...and please use TABs only.

I'm wondering if 
ref->newService->host = hostName;
(maybe on line 155 ;)
belongs in QZeroConfPrivate::resolverCallback() as hostName is just working its way to addressReply()
