### ISSUE TITLE
Using thread safe signals for the api

### ISSUE THREAD

**Issue by mattes-bru** [jbagg/QtZeroConf#15]
Signal / slots can be considered thread safe in Qt but the API of QtZeroConf breaks this by using the QZeroconf data type. What about using the SharedData concept of Qt?

**Comment by jbagg** [comment]
Are you referring to http://doc.qt.io/qt-5/implicit-sharing.html ?

**Comment by mattes-bru** [comment]
Exactly. I already started a new branch in my fork but there are some problems to solve.

**Comment by jbagg** [comment]
I am very open to this as it looks like the right thing to do.  I am aware of the implicit sharing inside Qt, but have not used it myself (so I may be slow to implement this).  You have indicated you have started work on this, so please feel free to continue.

**Comment by mattes-bru** [comment]
the code is already working, you’ll find it under: https://github.com/mattes-bru/QtZeroConf/tree/shareddata <https://github.com/mattes-bru/QtZeroConf/tree/shareddata>
I didn’t contributed it to your repo as I experienced some sporadic issues: 

In Linux the services weren’t removed from the list as there was no IP address in  the service which came from the signal 
in the bonjour implementation there was a deadlock with the void QZeroConfPrivate::cleanUp(DNSServiceRef toClean) method.

**Comment by mattes-bru** [comment]
short update...the issues should been solved. 

@jbagg what would be the best way to merge?

**Comment by jbagg** [comment]
I would like to do 2 things first, 1. review your changes which I can do as you have given me your url and 2. Do some testing.  Which platforms has you tested on or which haven't you tested on?  Then you can make a pull request.  Make sense?

Jon

**Comment by mattes-bru** [comment]
Sounds like a plan. 

I tested mac and linux so far. The example is already working with the new Signals.

**Comment by jbagg** [comment]
Two simple things so far.  1. It looks like your branch shareddata is missing a few commits from my master.  Could you update your shareddata branch?  2.  I would like the white space on each line before the code to only contain tabs.

**Comment by mattes-bru** [comment]
Done

**Comment by jbagg** [comment]
Finally updated the readme, closing.
