### ISSUE TITLE
Add Contact Info to Readme

### ISSUE THREAD

**Issue by benolswang** [jbagg/QtZeroConf#21]
The Readme lists the clause below to contact jbagg for a copy of QZeroConf with a BSD licence, but no contact information is given, nor is any present in the jbagg Github profile. Please add this.

> Apple App Store deployment
> Publishing GPL software in the App Store is a violation of the GPL. If you need to publish an app in the Apple App Store that uses QZeroConf, **please contact me** for a copy of QZeroConf with a BSD licence.

**Comment by jbagg** [comment]
I don't really want spam bots to grab my email.  I would think that people would clone the repo and then they can get my email from the git commit log.

**Comment by benolswang** [comment]
OK. I'll do that.
