### ISSUE TITLE
Unable to integrate in Qt 5.7.1.

### ISSUE THREAD

**Issue by wumpus7** [jbagg/QtZeroConf#3]
I'd love to use this library on my current project, but have not been able to link to it, despite days of trying.  I'm starting out trying to build for iOS.

I've tried several methods of linking, both the two suggested, and also pulling the project in as a submodule.  None of them work, so there must be more steps needed in the instructions?  Or something has broken in the past year?  Specific errors below:

Submodule

Attempts to compile fail thusly:

Starting:  "/usr/bin/make"
rm -f libQtZeroConf_debug.a
.../usr/bin/ar cq libQtZeroConf_debug.a
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...

Building into your project

Clone or download QZeroConf. If you download, unzip.
Copy the qtzeroconf directory to be under your project's directory.
Include the qtzeroconf.pri file in your projects .pro file

include(qtzeroconf/qtzeroconf.pri)

In the case of my project, there is a main app and several other libraries, so the question is where to include the qtzeroconf.pri file?  If I stick it into the main project file (at the bottom), everything compiles, but none of the objects in the qtzeroconf library can be linked to:

Undefined symbols for architecture arm64:
  "QZeroConf::startBrowser(QString, QAbstractSocket::NetworkLayerProtocol)", referenced from:
      QZeroConf::startBrowser(QString) in libConnectivityManager.a(connectivitymanager.o)
etc.

I've tried putting the include into the subdirs that use it, and that doesn't work either; I can provide more detail if that's the proper approach.

Compiling as a dynamic library

Clone or download QZeroConf. If you download, unzip.
Enter the qtzeroconf directory, run qmake and then make.

Running Qt5.7/5.7/clang_64/bin/qmake (the only one that works on my Mac, duh, creates a .dylib, and I suspect it might work with MacOS, but it's not going to work with iOS is it?  (Trying the ios qmake yields the same 'ar' errors as listed above for the submodule - probably not a coincidence?)

I've also tried endless permutations of trying to import the sources and add (another) library to my project; these all fail to link.  Qt Creator is extremely short on help, though, so I could easily be doing something wrong.

Any ideas?

Thanks,
Alex

**Comment by jbagg** [comment]
Hi Alex,

iOS was the only platform I have not tested on (no access to a MAC), but 
it should be able to work.  I think I know why.  In qtzeroconf.pri can 
you replace "macx" with "ios" and try?

macx {
         HEADERS+= $$PWD/qzeroconf.h $$PWD/bonjour_p.h
         SOURCES+= $$PWD/bonjour.cpp
         QMAKE_LFLAGS += -F 
/System/Library/Frameworks/CoreServices.framework/
         LIBS+= -framework CoreServices
         QMAKE_CXXFLAGS+= -I$$PWD
}

If that fixes the issue, let me know and I'll update the source.

On 17-02-13 09:15 PM, wumpus7 wrote:
>
> I'd love to use this library on my current project, but have not been 
> able to link to it, despite days of trying. I'm starting out trying to 
> build for iOS.
>
> I've tried several methods of linking, both the two suggested, and 
> also pulling the project in as a submodule. None of them work, so 
> there must be more steps needed in the instructions? Or something has 
> broken in the past year? Specific errors below:
>
> Submodule
>
> Attempts to compile fail thusly:
>
> Starting: "/usr/bin/make"
> rm -f libQtZeroConf_debug.a
> .../usr/bin/ar cq libQtZeroConf_debug.a
> ar: no archive members specified
> usage: ar -d [-TLsv] archive file ...
>
> Building into your project
>
> Clone or download QZeroConf. If you download, unzip.
> Copy the qtzeroconf directory to be under your project's directory.
> Include the qtzeroconf.pri file in your projects .pro file
>
> include(qtzeroconf/qtzeroconf.pri)
>
> In the case of my project, there is a main app and several other 
> libraries, so the question is where to include the qtzeroconf.pri 
> file? If I stick it into the main project file (at the bottom), 
> everything compiles, but none of the objects in the qtzeroconf library 
> can be linked to:
>
> Undefined symbols for architecture arm64:
> "QZeroConf::startBrowser(QString, 
> QAbstractSocket::NetworkLayerProtocol)", referenced from:
> QZeroConf::startBrowser(QString) in 
> libConnectivityManager.a(connectivitymanager.o)
> etc.
>
> I've tried putting the include into the subdirs that use it, and that 
> doesn't work either; I can provide more detail if that's the proper 
> approach.
>
> Compiling as a dynamic library
>
> Clone or download QZeroConf. If you download, unzip.
> Enter the qtzeroconf directory, run qmake and then make.
>
> Running Qt5.7/5.7/clang_64/bin/qmake (the only one that works on my 
> Mac, duh, creates a .dylib, and I suspect it might work with MacOS, 
> but it's not going to work with iOS is it? (Trying the ios qmake 
> yields the same 'ar' errors as listed above for the submodule - 
> probably not a coincidence?)
>
The Qt Linux+Android has two toolchains under Qt5.7/5.7/.  I suspect it 
is the same for Qt MAC+iOS.  Look for the iOS toolchain.

Jon

**Comment by wumpus7** [comment]
Howdy Jon,

Thanks for the quick response.

I added a modified block for iOS by copying the macx block and removing the QMAKE_LFLAGS and LIBS lines (which refer to CoreServices, which appears to be a Mac framework, not iOS), and now I can build Release.  I can't build either MacOS or iOS Debug, though.  The linker complains:

ld: library not found for -lQtZeroConf

I wonder if this is an issue with _debug or similar being postpended to the library name, or needing to be?  I tried removing the $$QT_LIBINFIX from the TARGET in QtZeroConf.pro, but that didn't seem to make any difference.  Any ideas on this one?

Thanks again,
Alex

**Comment by wumpus7** [comment]
Ah.  Getting rid of the $$qtLibraryTarget() part fixes it.  I'm guessing that's needed for Windows or somesuch?

**Comment by jbagg** [comment]
That is great that you got it to compile.  Does it work ok?  Are you 
able to advertise and discover on the iphone?

I just purchased an iphone 3 on ebay, but I need to update the mac as it 
only has snow (10.6.8) on it and Qt requires xcode 5.1.1. I'll be a 
couple of weeks.

**Comment by wumpus7** [comment]
I'm only using discovery, which appears to be working.  I am having some threading issues right now, but those are probably in my code, not yours.

**Comment by jbagg** [comment]
On 2017-02-15 04:16 PM, wumpus7 wrote:
>
> I'm only using discovery, which appears to be working. I am having 
> some threading issues right now, but those are probably in my code, 
> not yours.
>
QtZeroConf registers callbacks with dns_sd, so the OS may fire these at 
any time which will activate QtZeroConf's signals independent of Qt main 
loop.  The slots for QtZeroConf's signals should be thread safe or use 
Qt::QueuedConnection

Jon

**Comment by jbagg** [comment]
wumpus7,

Can you re-try your previous attempts at compiling?  ios has been added to .pri files and it compile for me (getting stuck at code signing error)

I also added Q_DECL_EXPORT which should fix your dynamic linking.  Window msvc people were having a similar issue with dynamic linking.

**Comment by jbagg** [comment]
wumpus7,  It seems like I can't run my project on an ios device unless I pay apple $100 / year.  QtCreator is error at the end of the build because it can't sign the app.  I've added my apple dev ID to xcode, it says that I am not on any teams.  When I log in to the apple dev site, I am missing "Certificates, Identifiers & Profiles" which is under "Personal Resources" (also missing).  I assume I must pay apple to get a certificate so Qt can finish the build.  Any suggestions?

**Comment by wumpus7** [comment]
Howdy Jon,

According to my colleague, you no longer need to pay to be able to run.  Of course, since we're both registered developers, though, neither of us has ever tried that.  Here's the link:

https://9to5mac.com/2016/03/27/how-to-create-free-apple-developer-account-sideload-apps/

Good luck - signing has only become a larger and larger pain in the ass over the years.

My other colleague submitted a pull request with our iOS changes, and it looks like it went through; we're certainly getting it all integrated at this point, thanks!

**Comment by Feyiafolabi** [comment]
Hey Alex,

Where was the $$qtLibraryTarget() that you took out that allowed your project to compile. Would be a huge help to me.

Thank you.

**Comment by jbagg** [comment]
Current code will not compile?

Jon

**Comment by jbagg** [comment]
Feyiafolabi, I am able to compile the example in Qt Creator as is on MAC for iOS as the target ....with the exception of not being able to sign it as Apple requests $100.00.  I don't remember if I tried building QZeroConf as a dynamic library for iOS or not.  Can you please try building the example in QtCreator for iOS?  For your issue, can you specify exactly what you are doing...building in xcode or Qtcreator.....building QZeroConf into your project or as a dynamic library?

**Comment by jbagg** [comment]
Please note that if you are building QZeroConf into your project you must add the following to your projects .pro file...

DEFINES+= QZEROCONF_STATIC

**Comment by Feyiafolabi** [comment]
Thanks for the quick reply Jon, I just started using Qtcreator a couple days ago so I am really a beginner. I tried compiling a project but an error comes up saying the qtzeroconf file cant be found. I then downloaded your project with the intention of building it into my current project but I do not really know how to go about that exactly, and to compound that your Qtzeroconf is not compiling on its own, the errors are "qtzeroconf-master/bonjour-sdk:no such file or directory" and "qtzeroconf-master:no such file or directory". I use a regular PC not a MAC.

Any help will be really appreciated.

**Comment by Feyiafolabi** [comment]
A detailed step by step procedure on how to go about fixing these issues will be greatly appreciated.

**Comment by jbagg** [comment]
Is your project on Github? or can you send me a zip of your project?

Jon

**Comment by Feyiafolabi** [comment]
drhalftone/LAURobotWidget

**Comment by jbagg** [comment]
To build QtZeroConf into your (GPL3 complaint) project, apply the 
attached patch and copy the QtZeroConf source into a directory in your 
project called qtzeroconf (same instructions as in README.md)

To link your project against QtZeroConf.dll, the way I tested it tonight 
was with MingGW and I put the QtZeroConf.dll and qzeroconf.h in the 
LAURobotWidget source directory and put this in the .pro file

LIBS += .\QtZeroConf.dll

Your .pro file may work as is if you put QtZeroConf.dll and qzeroconf.h 
in the right places (msvc I think needs the .lib or something too)

If using MingGW, avoid spaces in path names.

Linking dlls can be tricky.  Your dynamic linking issues are nothing to 
do with QtZeroConf....and instructions for dynamic linking are not given 
in the README.md because it is the same as using any other dll file.

**Comment by Feyiafolabi** [comment]
Thank you very much for your help, how do i go about the first step of copying the qtzeroconf source into the directory ?

**Comment by jbagg** [comment]
clone or download qtzeroconf and then copy it using file explorer to 
your LAURobotWidget directory, so you have the following directory 
structure.....

LAURobotWidget\laurobotwidget.cpp
LAURobotWidget\laurobotwidget.h
LAURobotWidget\lautcpserialportwidget.cpp
etc
LAURobotWidget\qtzeroconf\bonjour.cpp
LAURobotWidget\qtzeroconf\bonjour_p.h
LAURobotWidget\qtzeroconf\qtzeroconf.pro
etc

**Comment by Feyiafolabi** [comment]
Thank you.

When i try to run QtZeroConf a 'custom executable' pops up telling me to choose an executable.

**Comment by jbagg** [comment]
Please give more context.  If you have built QtZeroConf into your project or as a dll there is nothing to run.  I've attached LAURobotWidget project that will builds with QtZeroConf.
[LAURobotWidget_with_QtZeroConf.zip](https://github.com/jbagg/QtZeroConf/files/1063858/LAURobotWidget_with_QtZeroConf.zip)

**Comment by Feyiafolabi** [comment]
I fixed my code due to your help and got it to compile!

Thank you very much Jon!

**Comment by jbagg** [comment]
wumpus7,

I broke down and paid the $112 and now I can run the QtZeroConf example on my iphone 3GS.  I've noticed that when I put the device to sleep after starting the example, the discovery callback stops working after the device is woken back up.  I need to restart the example app to get discovery working.  Your post above mentions that you are using discovery.  Are you experiencing the same issue after putting the phone to sleep?  If not can you share your ios+xcode version combination?  I am using Xcode 7.3 and the phone is a iPhone 3GS running ios 6.

**Comment by wumpus7** [comment]
Howdy Jon,

We're on the latest Xcode (8.3.3) and no longer support anything below, uh, iOS 8, I think?

I don't trust anything to run properly in the background, so I shut down discovery when applicationDidEnterBackground: is called, and then restart it when applicationDidBecomeActive: fires.  I honestly don't know what the current state of backgrounded apps is, but I'm pretty sure that in iOS 6 you can't expect anything other than a very short list of processes (mostly audio related) to continue to run.

Hope that helps,
Alex
