### ISSUE TITLE
SIGABRT if Avahi is not running on Linux

### ISSUE THREAD

**Issue by vicr123** [jbagg/QtZeroConf#60]
If Avahi isn't running, `pri->client` ends up null, and there is no way to check for this condition. Attempting to start a service publish or a browser results in Avahi throwing up a `SIGABRT`

It would be great if there was a way to check if required services are available and running before running any of the functions that require a valid client.

**Comment by jbagg** [comment]
I modified startBrowser() and startServicePublish() to emit an error and return if pri->client is null (on latest master).  Let me know if this fixes your issue.

**Comment by vicr123** [comment]
Works great, thanks for that!
