### ISSUE TITLE
Add Qt6-Android support 

### ISSUE THREAD

**Issue by mariuszmaximus** [jbagg/QtZeroConf#63]
I try build QtZeroConf  on Qt 6.6 for my Android phone 

First problem 
`QT += androidextras`
androidextras not exists in Qt6  https://www.qt.io/blog/qt-extras-modules-in-qt-6

I have problem with this functions:
`QtAndroid::androidActivity().object()`
`QtAndroid::runOnAndroidThread(`

**Comment by mariuszmaximus** [comment]
Work in progress: https://github.com/mariuszmaximus/QtZeroConf/tree/Qt6

Changes:
- QT += androidextras  ==> QT += gui  
- QAndroidJniEnvironment ==> QJniEnvironment
- QAndroidJniObject ==>QJniObject
- QtAndroid::runOnAndroidThread ==> QNativeInterface::QAndroidApplication::runOnAndroidMainThread

Todo: 
[1]
```c++
	nsdManager = QJniObject("qtzeroconf/QZeroConfNsdManager", "(JLandroid/content/Context;)V", reinterpret_cast<quint64>(this), QtAndroid::androidActivity().object());
	if (nsdManager.isValid()) {
		jclass objectClass = env->GetObjectClass(nsdManager.object<jobject>());
		env->RegisterNatives(objectClass, methods, sizeof(methods) / sizeof(methods[0]));
		env->DeleteLocalRef(objectClass);
	}
```
`QtAndroid::androidActivity().object()`  **I don't know what it is in Qt6**

**Comment by hancerli** [comment]
Are you planning to submit a merge request any time soon?

**Comment by jbagg** [comment]
Did you finish your todo list?

**Comment by hancerli** [comment]
Seems like it's fixed [here](https://github.com/jbagg/QtZeroConf/compare/master...mariuszmaximus:QtZeroConf:Qt6#diff-9ca2da7f9b477ec71f0692a0a2dcc1610cde853c7241b23aafc7ce5970d76247) in `androidnsd.cpp` on line 56. Isn't that compiling @mariuszmaximus ?

**Comment by jbagg** [comment]
ok.  I have not tried compiling it yet.  Will do tonight.  Is it ok if I re-order the commits and squash some together?

**Comment by hancerli** [comment]
Ah, I think `QNativeInterface::QAndroidApplication::context()` should be replaced with `QNativeInterface::QAndroidApplication::context().object()`. I'm testing with 6.7.0 btw.

**Comment by jbagg** [comment]
Qt6 Android support is now on master
