### ISSUE TITLE
Extra files

### ISSUE THREAD

**Issue by mbsmith** [jbagg/QtZeroConf#9]
It seems like there are full implementations of Bonjour, and Avahi in source.  While it's not bothering current operations it could be a little confusing.  And if someone actually tried to link to those they could break ABI compatibility.

I think perhaps they should be removed, and rather than relying on a bundled implementation fix it via qmake.

**Comment by jbagg** [comment]
Bonjour "client" source code is needed on Windows.  This is used to 
connect to the dnssd server.  The full implementation of Avahi is needed 
on Android.  They will not be complied on other platforms and removing 
them would not allow QtZeroConf to work on windows or Android.

**Comment by mbsmith** [comment]
This patch didn't close either.  It only added txt handling.  It works on FreeBSD, Windows, and OS X tested.

**Comment by jbagg** [comment]
I thought the txt handling was "Added txt support. (#8)", not #9?

The plan is to add txt record support at some point.  I have not decided 
if I want to simply copy the all txt records to a byte array (like your 
patch) or get QZeroConf to break it up into a hash table or QMap.

Jon
